### PR TITLE
Eclipse patches

### PR DESCRIPTION
**Pull request by trancexpress**
We have some new patches since June, here is the PR.

### CODE REVIEW

**Comment by iloveeclipse** [comment]
`This branch has conflicts that must be resolved. Conflicting files: gtk-3.0/eclipse-patches/theme-patches.css`

Why that?

**Comment by trancexpress** [comment]
> `This branch has conflicts that must be resolved. Conflicting files: gtk-3.0/eclipse-patches/theme-patches.css`
> 
> Why that?

I tried to port our fixes 1 by 1 in separate commits, then I noticed this is for whatever reasons not trivial.

So I just replaced the contents of the GTK3 theme files with our own. This may have been too aggressive, but is in the end what we want to have in GitHub. I suggest just taking the version from my repository; it mirrors what we have and what we must expose license-wise.

**Comment by iloveeclipse** [comment]
I've missed this one. Can you please rebase the patch and resolve the merge conflict?

**Comment by trancexpress** [comment]
Commit aside, I've diffed the theme files. The only diff I see is in: `gtk-2.0/gtkrc`

```
4a5,7
> # gtk-alternative-button-order = 1
> # gtk-theme-name = "Clearlooks-Phenix"
> # gtk-cursor-theme-name = "KDE Classic"
407d409
```

Is this OK or do we need to push this as well?

Those lines are in our theme RPM but are not in my github repo.

**Comment by iloveeclipse** [comment]
Thanks.

**Pull request merged**
